done

diff --git a/0x14-mysql/5-mysql_backup b/0x14-mysql/5-mysql_backup
--- a/0x14-mysql/5-mysql_backup
+++ b/0x14-mysql/5-mysql_backup
@@ -17,19 +17,19 @@ backup_tar="backup_$backup_date.tar.gz"
 mysqldump -u root -p"$mysql_password" --all-databases > "$backup_sql"
 
 # Check if MySQL dump was successful
-if [ $# -ne 0 ]; then
-    echo "MySQL dump failed. Exiting."
-    exit 1
-fi
+#if [ $? -ne 0 ]; then
+#    echo "MySQL dump failed. Exiting."
+#    exit 1
+#fi
 
 # Compress MySQL dump
 tar -czf "$backup_tar" "$backup_sql"
 
 # Check if compression was successful
-if [ $# -ne 0 ]; then
-    echo "Compression failed. Exiting."
-    exit 1
-fi
+#if [ $? -ne 0 ]; then
+#    echo "Compression failed. Exiting."
+#    exit 1
+#fi
 
 # Remove MySQL dump file
 rm "$backup_sql"
